# Generated by Django 5.1.3 on 2024-12-05 07:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('text', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('area', models.CharField(choices=[('insurance', 'Insurance'), ('repair', 'Repair'), ('parts', 'Parts'), ('charging', 'Charging'), ('maintenance', 'Maintenance'), ('rent', 'Rent'), ('leasing', 'Leasing'), ('other', 'Other')], default='other', max_length=50, verbose_name='Service Area')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the service was created. Visible only to staff.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the service was last updated. Visible only to staff.', verbose_name='Updated At')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-id'],
            },
        ),
    ]
