# Generated by Django 5.1.3 on 2024-11-20 06:02

import EVTool.vehicles.models.base_ev
import EVTool.vehicles.models.ev_car_bike_photo
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='brandlogos/')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand')),
            ],
            options={
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EVBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.IntegerField(help_text='Price in EUR. Only whole numbers', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('battery_capacity', models.DecimalField(decimal_places=2, help_text='In kWh. Up to two decimals', max_digits=5)),
                ('range', models.IntegerField(default=None, help_text='WLTP rating or other tool in km', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('description', models.TextField(blank=True)),
                ('horsepower', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('year', models.IntegerField(default=None, validators=[EVTool.vehicles.models.base_ev.validate_year])),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('mileage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('body_type', models.CharField(choices=[('ATV', 'ATV'), ('Roadster', 'Roadster'), ('Cross', 'Cross'), ('Track', 'Track'), ('Тricycle', 'Тricycle')], default='unknown', max_length=15)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.bikemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EVBikePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to="photos/bikes/", validators=[EVTool.vehicles.models.ev_car_bike_photo.validate_image_size])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_photos', to='vehicles.evbike')),
            ],
        ),
        migrations.AddField(
            model_name='evbike',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_photos', to='vehicles.evbikephoto'),
        ),
        migrations.CreateModel(
            name='EVCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asking_price', models.IntegerField(help_text='Price in EUR. Only whole numbers', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('battery_capacity', models.DecimalField(decimal_places=2, help_text='In kWh. Up to two decimals', max_digits=5)),
                ('range', models.IntegerField(default=None, help_text='WLTP rating or other tool in km', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('description', models.TextField(blank=True)),
                ('horsepower', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('year', models.IntegerField(default=None, validators=[EVTool.vehicles.models.base_ev.validate_year])),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('trim_level', models.CharField(default='unknown', max_length=50)),
                ('mileage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('drivetrain', models.CharField(choices=[('Front-wheel drive', 'Front-wheel drive'), ('Rear-wheel drive', 'Rear-wheel drive'), ('All-wheel drive', 'All-wheel drive')], default='unknown', max_length=17)),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Station wagon', 'Station wagon'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Pickup Truck', 'Pickup Truck'), ('Minivan', 'Minivan'), ('Cabriolet', 'Cabriolet')], default='unknown', max_length=15)),
                ('doors', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=4)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.carmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EVCarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to="photos/bikes/", validators=[EVTool.vehicles.models.ev_car_bike_photo.validate_image_size])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='vehicles.evcar')),
            ],
        ),
        migrations.AddField(
            model_name='evcar',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='vehicles.evcarphoto'),
        ),
        migrations.AddField(
            model_name='evcar',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.municipality'),
        ),
        migrations.AddField(
            model_name='evbike',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicles.municipality'),
        ),
    ]
