# Generated by Django 5.1.3 on 2024-11-20 06:35

import EVTool.vehicles.models.ev_car_bike_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcarphoto',
            name='image',
            field=models.ImageField(upload_to='photos/cars/', validators=[EVTool.vehicles.models.ev_car_bike_photo.validate_image_size]),
        ),
    ]
