# Generated by Django 5.1.3 on 2024-11-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
