# Generated by Django 5.1.3 on 2024-11-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_municipality_options_alter_color_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvCarPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evcar_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('base_ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.evcar')),
            ],
        ),
    ]
