# Generated by Django 5.1.3 on 2024-11-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_evcarphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evbike',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='evcar',
            name='photos',
        ),
    ]
