# Generated by Django 5.1.3 on 2024-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_evbike_photos_remove_evcar_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evbike',
            name='body_type',
            field=models.CharField(choices=[('ATV', 'ATV'), ('Roadster', 'Roadster'), ('Cross', 'Cross'), ('Track', 'Track'), ('Tricycle', 'Tricycle'), ('Scooter', 'Scooter'), ('Sport', 'Sport'), ('Touring', 'Touring'), ('Cruiser', 'Cruiser'), ('Enduro', 'Enduro'), ('Adventure', 'Adventure')], default='unknown', max_length=15),
        ),
    ]
