# Generated by Django 5.1.3 on 2024-11-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_evcarphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evcarphoto',
            old_name='base_ev',
            new_name='car',
        ),
    ]
