# Generated by Django 5.1.3 on 2024-11-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_rename_base_ev_evcarphoto_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvBikePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evbike_photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicles.evbike')),
            ],
        ),
    ]
