# Generated by Django 5.1.3 on 2024-11-16 10:51

import EVTool.vehicles.models.ev_photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_evbikephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evbikephoto',
            name='image',
            field=models.ImageField(upload_to='evbike_photos/', validators=[EVTool.vehicles.models.ev_photo.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='evcarphoto',
            name='image',
            field=models.ImageField(upload_to='evcar_photos/', validators=[EVTool.vehicles.models.ev_photo.validate_image_size]),
        ),
    ]
