# Generated by Django 5.1.3 on 2024-11-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_evbikephoto_image_alter_evcarphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evcar',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Station wagon', 'Station wagon'), ('Coupe', 'Coupe'), ('SUV', 'SUV'), ('Pickup Truck', 'Pickup Truck'), ('Minivan', 'Minivan'), ('Cabriolet', 'Cabriolet')], default='unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='evcar',
            name='drivetrain',
            field=models.CharField(choices=[('Front-wheel drive', 'Front-wheel drive'), ('Rear-wheel drive', 'Rear-wheel drive'), ('All-wheel drive', 'All-wheel drive')], default='unknown', max_length=17),
        ),
    ]
