# Generated by Django 5.1.3 on 2024-11-19 05:58

import EVTool.vehicles.models.ev_photo
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vehicles', '0008_alter_evbike_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evcarphoto',
            name='car',
        ),
        migrations.CreateModel(
            name='EVPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='ev_photos/', validators=[EVTool.vehicles.models.ev_photo.validate_image_size])),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='EvBikePhoto',
        ),
        migrations.DeleteModel(
            name='EvCarPhoto',
        ),
    ]
