# Generated by Django 5.1.3 on 2024-11-15 11:46

import EVTool.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', EVTool.accounts.managers.AppUserManager()),
            ],
        ),
    ]
