# Generated by Django 5.1.3 on 2024-11-15 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Name must start with a letter and contain letters, apostrophes, or hyphens. Length must be between 2 to 50 characters.', regex="^[A-Za-z][A-Za-z'’\\-]{1,49}$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Name must start with a letter and contain letters, apostrophes, or hyphens. Length must be between 2 to 50 characters.', regex="^[A-Za-z][A-Za-z'’\\-]{1,49}$")]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Nickname must be between 3 and 50 characters long and can include letters, numbers, underscores, and hyphens.', regex='^[A-Za-z0-9_’\\-]{3,50}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be between 9 and 12 digits long, can start with +, and contain only digits.', regex='^\\+?\\d{9,12}$')]),
        ),
    ]
